#!/bin/sh
# SPDX-License-Identifier: GPL-2.0+

. ./common

testdir=$SCRATCH_MNT/test5
imgfile=${testdir}.img

rm -rf $testdir
mkdir -p $testdir

teardown_hook() {
	rm -rf $testdir
}

# test pipe file
mknod $testdir/pipefile p

erofs_mkfs "$imgfile $testdir"
sz=$(file_size "$imgfile")

teardown_hook

if [ $sz -le 0 ]; then
	echo "invalid size $sz"
	exit 1
fi

