#!/bin/sh
# SPDX-License-Identifier: GPL-2.0+

. ./common

testdir=$SCRATCH_MNT/test3
imgfile=${testdir}.img

teardown_hook() {
	umount "$TEST_DIR" 2> /dev/null
	rm -rf $outputfile
}

# test long symlink (non-fast symlink)
MD5='a487a80b24d56a83b952fa70ff961297'

erofs_mount "$imgfile"

realmd5=$(readlink $TEST_DIR/symlink | tr -d '\n' | md5sum | cut -d' ' -f1)

[ $realmd5 = $MD5 ] || \
	exit_failed "-->checkmd5 FAILED"

erofs_umount
teardown_hook

