#!/bin/sh
# SPDX-License-Identifier: GPL-2.0+

. ./common

testdir=$SCRATCH_MNT/test4
imgfile=${testdir}.img

teardown_hook() {
	umount "$TEST_DIR" 2> /dev/null
	rm -rf $outputfile
}

ttypenul='character special file:1,3'
ttypelop='block special file:7,7b'

erofs_mount "$imgfile"

[ "$(stat -c "%F:%t,%T" $TEST_DIR/nulldev | tr -d '\n')" = "$ttypenul" ] || \
	exit_failed "-->checknulldev FAILED"
[ "$(stat -c "%F:%t,%T" $TEST_DIR/loopdev | tr -d '\n')" = "$ttypelop" ] || \
	exit_failed "-->checkloopdev FAILED"

erofs_umount
teardown_hook

