#!/bin/sh
# SPDX-License-Identifier: GPL-2.0+

. ./common

testdir=$SCRATCH_MNT/test18
outputfile=${testdir}.img

rm -rf $testdir
mkdir -p $testdir

[ -z "$lz4hc_on" ] && \
	exit_skipped "lz4HC compression is off, skipped."

dirs=`find ../ -maxdepth 1 -type d -printf '%p:'`
IFS=':'
for d in $dirs; do
	[ $d = '../' ] && continue
	[ -z "${d##\.\./tests*}" ] && continue
	[ -z "${d##\.\./\.*}" ] && continue
	cp -nR $d $testdir
done

teardown_hook() {
	rm -rf $testdir
}

erofs_mkfs "-zlz4hc $outputfile $testdir"
sz=$(file_size "$outputfile")

teardown_hook

if [ $sz -le 0 ]; then
	echo "invalid size $sz"
	exit 1
fi

